sudo: false
language: elixir
elixir:
  - 1.3.0
otp_release:
  - 18.0
  - 19.0
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database geo_postgrex_test;' -U postgres
  - psql -c 'create extension postgis;' -U postgres -d geo_postgrex_test